# Generated by Django 5.2.8 on 2025-11-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
