# Generated by Django 5.2.8 on 2025-11-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_days_note_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
