# Generated by Django 5.2.8 on 2025-11-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='days',
        ),
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
